### PR TITLE
Fixing tests

### PR DESCRIPTION
**Pull request by TurtleSquad007**
fixed everything to match new dirgram

### CODE REVIEW

**Comment by TurtleSquad007** [comment]
Fixed issues with old request

**Review by giancarlopernudisegura — CHANGES_REQUESTED** [review]
From our meeting: You can't really test the plots so remove those tests.

**Comment by TurtleSquad007** [comment]
I wanted include them because he'd ask to a test for every user story but I'll get rid of it for this iteration.

**Comment by giancarlopernudisegura** [comment]
The only thing we can do is check for the subtitle, I don't think we can check for a chart view.

**Comment by giancarlopernudisegura** [comment]
Oh, actually you can query for a specific view. So we could (in a separate PR) just try to query for the chart via view ID and check that it doesn't return null.

**Comment by TurtleSquad007** [comment]
I'm good for doing that. I'll make a new branch and do that next. Should I test for mean, median, and quartiles stuff?

**Comment by giancarlopernudisegura** [comment]
Yeah for the stats test, just add like a binomial trial (2 passes 1 fail) and then query for the expected stat text. (ie a median of **1**)

**Review by giancarlopernudisegura — CHANGES_REQUESTED** [review]
You can go ahead and leave out the testing for ignore results since it's not implemented yet. Instead, you can go on the branch I'm working on (`ignore-trials`) and add (and implement) it there. You can also leave out subscribing since it's not implemented yet. For stats, as discussed remove it, and then make a separate PR.

**Review by giancarlopernudisegura — APPROVED** [review]

**Pull request merged**
