### PR TITLE
fixed binomial stats tests

### PR DESCRIPTION
**Pull request by TurtleSquad007**
-Works with firebase now

### CODE REVIEW

**Review by giancarlopernudisegura — DISMISSED** [review]
If you're going to write an intent test, you should interact with that application using robotium.

**Comment by TurtleSquad007** [comment]
It's a consequence of firebase. If they're intent cases I can't give firebase a test Context to allow for out tests to run. The other solution is remake the test in such a way as to not interact with firebase.

**Comment by TurtleSquad007** [comment]
If you on main right now and they to run the junit tests we currently have you'll see that they fail because firebase isn't set up.

**Review by NickNissen — APPROVED** [review]
Testing works well with firebase

**Pull request merged**
