### PR TITLE
User stub

### PR DESCRIPTION
**Pull request by giancarlopernudisegura**
This is in response to #15. Since this has hard-coded values I didn't provide any unit tests. If you'd like some anyways let me know. I've also typed some of the class variables but have left them commented since those classes haven't been created yet.

Right now, an experimenter has two constructors. The constructor without arguments creates the stub class with hard-coded values.

Let me know if I need to make any changes before a pull.

### CODE REVIEW

**Review by NickNissen — CHANGES_REQUESTED** [review]
Users can be both Owners and Experimenters, the class should be called User to avoid confusion between the class and the roles of that class

**Comment by giancarlopernudisegura** [comment]
I'm following [the UML](https://raw.githubusercontent.com/CMPUT301W21T03/Experiment-Automata/main/doc/uml/UML.png) which only has the Experimenter class. Do you just want me to rename `Experimenter` to `User`?

**Comment by NickNissen** [comment]
Yes, we should probably also update the UML.

**Comment by musichead42** [comment]
I'm not sure I agree with just changing all instances of Experimenter with User. I think we should have the structure Dr. Hindle mentioned in lecture today: Owner -> User <- Experimenter. We can update this in the UML as we see fit, since there should be some separate methods between these two classes. Also, can you generate the .png file in the UML when you change it @giancarlopernudisegura?

**Comment by giancarlopernudisegura** [comment]
Sound like something we should talk about during our next meeting. For now, I'll revert the commit that changes the UML but keep the change in the java code.

@musichead42 For future reference, how do I generate the new png?

**Comment by musichead42** [comment]
@giancarlopernudisegura agreed we should discuss this in our next meeting. To generate the PlantUML, go here to download the plantuml.jar file: https://plantuml.com/. Then on your command line, run "java -jar plantuml.jar [nameOfUMLFile]". This should generate a PNG.

**Comment by giancarlopernudisegura** [comment]
@CMPUT301W21T03/reviewers This should be good to re-review

**Review by NickNissen — APPROVED** [review]

**Pull request merged**
