### PR TITLE
Search refinement

### PR DESCRIPTION
**Pull request by Jdvdb**
PR for issue #23 

- Updated ExperimentManager to contain methods that allow for querying descriptions from certain groups
- Refactored some functions from experiment manager for better names (i.e. queryPublishedExperiments is now getPublishedExperiments)
- Updated the UML with these changes
- Added and refined Javadoc for ExperimentManager and NavigationActivity
- Slightly revamped the way the search worked in order to ensure the proper items were to be selected each time.

Known bug: Prior to starting work on this, if you execute multiple searches then they begin to nest on each other. I don't think this is the intended functionality but I wasn't sure how to fix it immediately and I think proper search is a good feature for our MVP due March 19 (today). Because of this I made a temporary work around by having the ExperimentManager save the last fragment it was in (that wasn't a search). This was needed since there was no way to know what to query within a nested search. Experiment manager technically should not hold information on fragments so this will definitely be modified once the nested searching is fixed.

Up to reviewers if they want to pull this into main or if we should wait until nested searching is fixed

### CODE REVIEW

**Comment by giancarlopernudisegura** [comment]
How do they begin to nest on each other?

**Comment by Jdvdb** [comment]
If you make a search and then click on the search bar again and make another search without pressing the back button then you start getting this nesting thing going

**Review by giancarlopernudisegura — COMMENTED** [review]
Add the known issue you found in the list of issues at the beginning of the class.

**Review by giancarlopernudisegura — DISMISSED** [review]
I see what you mean now. Nested queries are fine, that's how many apps implement searching. The YouTube app for example does this so we should keep it the same. The type of query search we perform shouldn't depend on what listView the user is currently looking at. So when you search in "My Experiments" or "Published Experiments", the search results should be identical. The search should just look among all published experiments. Perhaps for Part 4, we may also return the owned but unpublished experiments too but for now just the published experiments. Last thing, could you remove the line `searchView.setQuery("", false);` in `NavigationActivity.java`?

**Comment by giancarlopernudisegura** [comment]
After these changes, you'll also need to fix the merge conflict before I can merge it into main.

**Comment by Jdvdb** [comment]
I (kind of) made the changes. Query now searches only published changes on each search. However, I did not remove the requested line as removing it caused an odd bug where the search would execute twice and you would have 2 screens to dismiss. I tried setting the string to query but that left the same bug so it's easiest to just leave that line and reset the search parameter after someone executes a search. If you feel like this needs to be changed I can work on it over the weekend and clean up some small visual things with the search such as the title updating.

**Review by NickNissen — APPROVED** [review]

**Pull request merged**
