### PR TITLE
Changed dir structure to better match documentation form docs  

### PR DESCRIPTION
**Pull request by TurtleSquad007**

### CODE REVIEW

**Comment by Pegmode** [comment]
Forcing the update since it's minor and looks fine.

**Comment by TurtleSquad007** [comment]
Added reviewers just to practice doing this

**Comment by Pegmode** [comment]
I think the way it's set up it needs BOTH reviewers to accept.

**Review by Pegmode — APPROVED** [review]
looks fine

**Comment by Pegmode** [comment]
never mine it doesn't. Request approved

**Comment by TurtleSquad007** [comment]
Lol, just practicing wanted see how reviews stuff worked!

**Pull request merged**
