### PR TITLE
Comments feature

### PR DESCRIPTION
**Pull request by TurtleSquad007**
Not yet done needs some fixes working on them now!

This is dealing with issue #9 and #34

### CODE REVIEW

**Comment by TurtleSquad007** [comment]
TODO: make scrolling list of questions and replies. 
(1) might need a custom list adapter
(2) associate experiment id's with questions 
(3) finish adding and editing

**Comment by giancarlopernudisegura** [comment]
How close is this to be ready for review?

**Comment by TurtleSquad007** [comment]
Hopefully before Mondays' class

**Comment by giancarlopernudisegura** [comment]
One thing from quickly looking at the branch: Can you remove the background from the reply button?

**Comment by TurtleSquad007** [comment]
> How close is this to be ready for review?

Yup done! Just need to finish displaying all the replies onto the the screen

**Comment by TurtleSquad007** [comment]
Done. Need to talk about edit as it looks it's not really a requirement of the project for the replies. We might be able to leave it off. 
It's not too hard to add though.

**Comment by giancarlopernudisegura** [comment]
If we have time in part 4, we can implement editing.

**Review by giancarlopernudisegura — CHANGES_REQUESTED** [review]
The + fab button now disappears on the experiments detail page. I can show you in tomorrow's meeting how to properly implement the fab button.

**Review by NickNissen — APPROVED** [review]

**Review by NickNissen — APPROVED** [review]

**Review by NickNissen — APPROVED** [review]

**Pull request merged**
