### PR TITLE
firebase setup

### PR DESCRIPTION
**Pull request by giancarlopernudisegura**
I set up the Firebase according to #44. I added the google services json to the gitignore for security and made changes to the gradle files accordingly. I also added everyone to the firebase project.

@CMPUT301W21T03/main Can each of you confirm that you can access [the firebase project](https://console.firebase.google.com/) in your browser? (Log in with your ualberta account)

### CODE REVIEW

**Comment by Jdvdb** [comment]
I have access to the firebase project!

**Comment by musichead42** [comment]
I also have access to the firebase, great work @giancarlopernudisegura !

**Comment by TurtleSquad007** [comment]
Works good on my end

**Review by NickNissen — APPROVED** [review]

**Comment by Pegmode** [comment]
works on my end as well

**Pull request merged**
