### PR TITLE
Share qr

### PR DESCRIPTION
**Pull request by giancarlopernudisegura**
Create the ability to share a QR code natively to other applications or to save to the device. This fixes our current method which is taking a screenshot.

Made for #161

### CODE REVIEW

**Comment by TurtleSquad007** [comment]
I messed up - there's my attempt resolve the merge conflicts broke it

**Review by TurtleSquad007 — CHANGES_REQUESTED** [review]
Revert the last commit I made and fix the merge conflicts. When I tried it didn't work

**Review by NickNissen — COMMENTED** [review]
Wait for the testing fix to be merged to main, then merge into this and test before approving. At least 1 reviewer had difficulties with merge conflicts so lets make sure we don't break anything here by ensuring the tests run.

**Review by NickNissen — APPROVED** [review]
Merge conflicts handled and tests pass as expected

**Pull request merged**
